### 一、基础创建与查看

1. 导入 pandas，用字典创建 DataFrame：

   name: Tom, Jerry, Mike

   score: 85, 92, 78

   gender: 男，女，男

   

2. 查看上述 DataFrame 的前 1 行、形状、列名、数据类型。

   

3. 用列表创建 DataFrame：

   data = [[1, "A"], [2, "B"], [3, "C"]]

   列名设为 id、tag

In [177]:
import pandas as pd 
data_dict = {
    "name": ["Tom", "Jerry", "Mike"],
    "score": [85, 92, 78],
    "gender": ["男", "女", "男"]
}
# 用字典创建DataFrame
df1 = pd.DataFrame(data_dict)
df1

    name  score gender
0    Tom     85      男
1  Jerry     92      女
2   Mike     78      男

In [178]:
df1.head(1)

  name  score gender
0  Tom     85      男

In [179]:
df1.shape

(3, 3)

In [180]:
df1.columns.tolist

In [181]:
data_list = [[1, "A"], [2, "B"], [3, "C"]]
# 定义列名
columns = ["id", "tag"]

# 用列表创建DataFrame并指定列名
df2 = pd.DataFrame(data_list, columns=columns)
df2

   id tag
0   1   A
1   2   B
2   3   C

### 二、列与行操作

1. 选取 score 和 gender 两列。

   

2. 选取索引 0、2 的行。

   

3. 筛选 score>80 的行。

   

4. 新增一列 grade：score≥90 为优秀，否则为良好。

   

5. 删除 gender 列。

In [182]:

df1[['score','gender']]

   score gender
0     85      男
1     92      女
2     78      男

In [183]:
df1.loc[[0,2]]

   name  score gender
0   Tom     85      男
2  Mike     78      男

In [184]:
df1[df1['score']>80]

    name  score gender
0    Tom     85      男
1  Jerry     92      女

In [185]:
import numpy as np
df1['grade']=np.where(df1['score']>=90,'优秀','良好')
df1

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

In [186]:
df3=df1.drop(columns='gender')
df3

    name  score grade
0    Tom     85    良好
1  Jerry     92    优秀
2   Mike     78    良好

### 三、缺失值

1. 创建含缺失值的 DataFrame：

   data = {"x":[1, None, 3], "y":[None, 5, 6]}

   检测缺失值并统计每列缺失数量。
2. 用 0 填充缺失值；删除含缺失值的行。

In [187]:
data={'x':[1,None,3],'y':[None,5,6]}
df4=pd.DataFrame(data)
df4

     x    y
0  1.0  NaN
1  NaN  5.0
2  3.0  6.0

In [188]:
df4.isnull().sum()

x    1
y    1
dtype: int64

In [189]:
df4_fill0=df4.fillna(0)
df4_fill0

     x    y
0  1.0  0.0
1  0.0  5.0
2  3.0  6.0

In [190]:
df4_drop=df4.dropna()
df4_drop

     x    y
2  3.0  6.0

### 四、分组聚合

1. 按 gender 分组，求 score 的均值和最大值。

   

2. 按 gender 分组，统计每组人数。

In [191]:
agg_result=df1.groupby('gender')['score'].agg(['mean','max'])
agg_result

        mean  max
gender
女       92.0   92
男       81.5   85

In [192]:
count_result1=df1.groupby('gender').size()
count_result1

gender
女    1
男    2
dtype: int64

### 五、排序与去重

1. 按 score 升序排序。

   

2. 给 DataFrame 添加一行重复数据（如 Tom,85, 男），去重。

In [193]:
df1_sorted=df1.sort_values('score')
df1_sorted

    name  score gender grade
2   Mike     78      男    良好
0    Tom     85      男    良好
1  Jerry     92      女    优秀

In [194]:
df1_dup=df1._append({'name':'Tom','score':85,'gender':'男','grade':'良好'},ignore_index=True)
df1_dup

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好
3    Tom     85      男    良好

In [195]:
df1_dedup=df1_dup.drop_duplicates()
df1_dedup

    name  score gender grade
0    Tom     85      男    良好
1  Jerry     92      女    优秀
2   Mike     78      男    良好

### 六、合并与拼接

1. 横向合并：

   df1 = pd.DataFrame ({"id":[1,2], "name":["X","Y"]})

   df2 = pd.DataFrame ({"id":[1,2], "age":[20,30]})

   按 id 合并。

   

2. 纵向拼接：

   df_a = pd.DataFrame ({"val":[1,2]})

   df_b = pd.DataFrame ({"val":[3,4]})

   拼接后重置索引。

In [196]:

df5 = pd.DataFrame({"id": [1, 2], "name": ["X", "Y"]})
df6 = pd.DataFrame({"id": [1, 2], "age": [20, 30]})
df5

   id name
0   1    X
1   2    Y

In [197]:
df6

   id  age
0   1   20
1   2   30

In [198]:
merged_df = pd.merge(df5, df6, on="id")
merged_df

   id name  age
0   1    X   20
1   2    Y   30

In [199]:
df_a = pd.DataFrame({"val": [1, 2]})
df_b = pd.DataFrame({"val": [3, 4]})

df_a

   val
0    1
1    2

In [200]:
df_b

   val
0    3
1    4

In [201]:
concat_df = pd.concat([df_a, df_b], ignore_index=True)
concat_df

   val
0    1
1    2
2    3
3    4

### 七、时间处理

1. 创建时间列：["2025-01-01","2025-01-02","2025-01-03"]，转为 datetime 格式。

   

2. 提取时间列的月份、星期。

In [202]:
time_list = ["2025-01-01", "2025-01-02", "2025-01-03"]
time_index = pd.to_datetime(time_list)  
time_index

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03'], dtype='datetime64[ns]', freq=None)

In [203]:
months = time_index.month
months

Index([1, 1, 1], dtype='int32')

In [204]:
weekdays_name = time_index.day_name() 
weekdays_name

Index(['Wednesday', 'Thursday', 'Friday'], dtype='object')

### 八、高级操作

1. 对 score 列做标准化（(值 - 均值)/ 标准差）。

   

2. 用透视表：行是 gender，值是 score，聚合函数为中位数。

In [205]:

# 1. 对score列做标准化
score_mean = df1['score'].mean()
score_std = df1['score'].std()
df1['score_standardized'] = (df1['score'] - score_mean) / score_std
df1

    name  score gender grade  score_standardized
0    Tom     85      男    良好                 0.0
1  Jerry     92      女    优秀                 1.0
2   Mike     78      男    良好                -1.0

In [206]:
# 2. 透视表：行是gender，值是score，聚合函数为中位数
pivot_table_result = df1.pivot_table(
    index='gender',    
    values='score',    
    aggfunc='median'   
)
pivot_table_result

        score
gender
女        92.0
男        81.5